### ISSUE TITLE
quantized size(0.009M)  vs. original size(373.094MB)?

### ISSUE THREAD

**Issue by mintisan** [Arshdeep-Singh-01/Human-Activity-Recognition-using-MutliHead-Convolutional-Attention#1]
As title shows, anything wrong?

![image](https://github.com/Arshdeep-Singh-01/Human-Activity-Recognition-using-MutliHead-Convolutional-Attention/assets/9136049/4a244d55-b4b3-430c-9d3f-84931799a45a)

**Comment by Arshdeep-Singh-01** [comment]
Yes, I am sure about these!

**Comment by Arshdeep-Singh-01** [comment]
![image](https://github.com/Arshdeep-Singh-01/Human-Activity-Recognition-using-MutliHead-Convolutional-Attention/assets/78218659/2453d658-de79-4228-8478-3ecdecd2f720)

**Comment by mintisan** [comment]
so nice.

I will have a try

Thanks.
